apiVersion: v2
description: Helm chart for the HMCTS CCD Definition Importer
name: ccd-definition-importer
home: https://github.com/hmcts/ccd-docker-definition-importer
version: 1.3.4
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
dependencies:
  - name: library
    version: 0.5.8
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
