image: 'hmctspublic.azurecr.io/ccd/definition-importer:latest'
memoryRequests: '512Mi'
cpuRequests: '250m'
memoryLimits: '2048Mi'
cpuLimits: '1500m'
# kvSecretRef: kvcreds
# gitSecretRef: kvcreds
# Definitions is a list. For example:
# definitions:
# - https://github.com/hmcts/chart-ccd/raw/master/data/CCD_Definition_Test_Exception_Record.template.xlsx
# - https://github.com/hmcts/chart-ccd/raw/master/data/CCD_Definition_Test.template.xlsx
definitions:
definitionFilename: ""
waitHosts: ""
waitHostsTimeout: 300
userRoles:
  - caseworker-bulkscan
microservice: ccd_gw
verbose: "false"
redirectUri: "https://ccd-case-management-web-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2redirect"
s2sUrl: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
definitionStoreUrl: http://{{ .Release.Name }}-definition-store-api
idamApiUrl: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
ingressHost: ""
importerFromSecret: true
importerUsername: 
    secretKeyRefName: ccd-importer-username
    secretKeyRefKey: key
importerPassword: 
    secretKeyRefName: ccd-importer-password
    secretKeyRefKey: key
apiGateway:
    s2sKey: AAAAAAAAAAAAAAAA
    idamClientSecret: 
      fromSecret: true
      secretKeyRefName: ccd-api-gateway-oauth2-client-secret
      secretKeyRefKey: key    