name: chart-ccd-definition-importer pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
- job: Validate
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
    parameters:
      chartName: ccd-definition-importer
      chartReleaseName: chart-ccd-definition-importer-ci-test
      chartNamespace: chart-tests
      helmInstallTimeout: "600"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: steps/charts/release.yaml@cnp-azuredevops-libraries
    parameters:
      chartName: ccd-definition-importer
      chartReleaseName: chart-ccd-definition-importer
      chartNamespace: chart-tests
