global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: aat
dummyConfigInCI: true   #Need this for pipleine build only
definitions:
 - https://github.com/hmcts/ccd-data-store-api/raw/master/src/aat/resources/CCD_CNP_27_AUTOTEST1.xlsx
userRoles:
  - caseworker-cmc
verbose: true


  