{{- $languageValues := deepCopy .Values}}
{{- if hasKey .Values "language" -}}
  {{- $languageValues = (deepCopy .Values | merge (pluck .Values.language .Values | first) )}}
{{- end -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "hmcts.releasename.v2" . }}
  {{- include "hmcts.labels.v2" . | indent 2 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: "{{ if .Values.debug }}before-hook-creation{{ else }}hook-succeeded{{ end}}"
spec:
  template:
    metadata:
      name: {{ template "hmcts.releasename.v2" . }}
      {{- ( include "hmcts.labels.v2" . ) | indent 6 }}
    spec:
      {{- ( include "hmcts.secretCSIVolumes.v3" . ) | indent 6 }}
      containers:
        - name: {{ template "hmcts.releasename.v2" . }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          {{- ( include "hmcts.secretMounts.v2" . ) | indent 10 }}
          env:
          {{- (include "hmcts.secrets.v2" .) | indent 10 }}
          - name: CCD_DEF_URLS
            value: {{ join "," .Values.definitions | quote }}
          - name: CCD_DEF_FILENAME
            value: {{ .Values.definitionFilename | quote }}
          - name: WAIT_HOSTS
            value: {{ .Values.waitHosts | quote }}
          - name: WAIT_HOSTS_TIMEOUT
            value: {{ .Values.waitHostsTimeout | quote }}
          - name: CREATE_IMPORTER_USER
            value: "false"
          {{- if and .Values.keyVaults .Values.global.enableKeyVaults }}
          - name: IMPORTER_SECRETS_MOUNT
            value: '/mnt/secrets/ccd'
          {{- end }}
          - name: IDAM_URI
            value: {{ tpl .Values.idamApiUrl $ }}
          - name: REDIRECT_URI  
            value: {{ tpl .Values.redirectUri $ }}
          - name: CLIENT_ID
            value: {{ tpl .Values.idamClientId $ }}
          - name: USER_ROLES
            value: {{ join "," .Values.userRoles }}
          - name: MICROSERVICE_BASE_URL
            value: http://{{ .Values.ingressHost }}
          - name: AUTH_PROVIDER_BASE_URL
            value: {{ tpl .Values.s2sUrl $ }}
          - name: MICROSERVICE
            value: {{ .Values.microservice }}
          - name: CCD_STORE_BASE_URL
            value: {{ tpl .Values.definitionStoreUrl $ }}
          - name: VERBOSE
            value: {{ .Values.verbose | quote }}
          {{- range $key, $val := $languageValues.environment }}
          - name: {{ $key }}
            value: {{ tpl ($val | quote) $ }}
          {{- end}}
          resources:
            requests:
              memory: {{ .Values.memoryRequests }}
              cpu: {{ .Values.cpuRequests }}
            limits:
              memory: {{ .Values.memoryLimits }}
              cpu: {{ .Values.cpuLimits }}
      restartPolicy: Never